const { Scheduler } = require('../src/jscheduler_ui/scheduler');

const { JSDOM } = require("jsdom");

const UUID4_REGEX = /^[0-9A-F]{8}-[0-9A-F]{4}-[4][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i;

describe("scheduler.pushEvent()", () => {
   
    const { window } = new JSDOM(`<!DOCTYPE html><div id="scheduler"></div>`);
    const rootElement = window.document.getElementById('scheduler');
    
   
    test("should return an autogenerated id if missing", () => {
        
        const scheduler = new Scheduler(rootElement);
        
        expect(
            scheduler.pushEvent({ _uuid: 1234, label: 'foo'})
        ).toEqual(
            { _uuid: 1234, label: 'foo' }
        );
        
        expect(
            scheduler.pushEvent({ label: 'bar'})
        ).toStrictEqual({
            _uuid: expect.stringMatching(UUID4_REGEX), 
            label: 'bar'
        });
        
        /*
         * @todo missing a getEvents() function to check if the event with 
         * generated id is returned. The getEvents() function should return
         * all events including the invalid ones. The valid events should be
         * filtered only at rendering
         */
        
    })
    
})
